name: logbox_color
description: Print colored box logs on terminal / console.
version: 1.0.0
repository: https://github.com/berkbb/logbox_color

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dart_console: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
